apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data
  namespace: flower-app
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001/"