apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data-claim
  namespace: flower-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi