apiVersion: v1
kind: Service
metadata:
  name: flower-server
  namespace: flower-app
  labels:
    app: flower-server
spec:
  type: NodePort
  ports:
   - port: 8080
     nodePort: 30555
  selector:
   app: flower-server